      - name: Setup Frontend
        hosts: all
        become: yes
        tasks:
        - name: Installing Nginx Server
          ansible.builtin.yum:
           name: nginx
           state: latest

      - name: Remove directory
        ansible.builtin.file:
         path: /usr/share/nginx/html
         state: absent

      - name: Create directory
        ansible.builtin.file:
         path: /usr/share/nginx/html
         state: directory

      - name: Downloading Frontend Content
        ansible.builtin.unarchive:
          src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
          dest: /usr/share/nginx/html
          remote_src: yes


      - name: Copy file
        ansible.builtin.copy:
          src: roboshop.conf
          dest: /etc/nginx/default.d/roboshop.conf


echo -e "${color} Update Frontend Configuration ${nocolor}"
cp /root/roboshop-shell/roboshop.conf /etc/nginx/default.d/roboshop.conf &>>/tmp/roboshop.log
stat_check $?

echo -e "${color} Starting Nginx Server ${nocolor}"
systemctl enable nginx &>>/tmp/roboshop.log
systemctl restart nginx &>>/tmp/roboshop.log
stat_check $?

