    -name: Mongodb Server Setup
    hosts: all
    become: yes
    tasks:
      - name: Copy MongoDB Repo file
        ansible.builtin.copy:
          src: mongodb.repo
          dest: /etc/yum.repos.d/mongodb.repo

      - name: Install MongoDB Server
        ansible.builtin.yum:
        name: mongodb-org
        state: latest

      - name: Update MongoDB Listen Address
        ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: 127.0.0.1
        replace: 0.0.0.0


      - name: Start Mongodb Server
        ansible.builtin.service:
          name: mongod
          state: restarted
          enabled: true