- name: Installing Nginx Server
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Remove application directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create application directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and extract content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy Nginx configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Copy roboshop configuration
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx Service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: true

- name: Starting ELK
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat