- name: Install Mysql Client
  ansible.builtin.yum:
    name: mysql
    state: installed

    -name: Load Schema
    ansible.builtin.shell: mysql -h mysql-dev.devopspractice73.online -uroot -p {{ mysql_root_password }} </app/schema/{{ component }}.sql
