- name: Copy SystemD File
  ansible.builtin.copy:
    remote_src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Start {{ component }} Service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    daemon_reload: true
    enabled: yes