#tags:
#  - company_name
#  - business
#  - business_unit
#  - cost_center
#  - project_name
#  - env
#  - Name
#
#
#

tags = {
company_name  = "XYZ Tech"
business      = "ecommerce"
business_unit = "retail"
cost_center   = "322"
project_name  = "roboshop"
}